/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Context;


import Context.configuration.BeanConfiguration;
import Context.service.BeanAnnotationcBusinessService;
import Context.service.ProgrammaticallyRegisterService;
import Context.service.StereotypeBusinessService;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) {
        var context =
                new AnnotationConfigApplicationContext(BeanConfiguration.class);
        BeanAnnotationcBusinessService beanAnnotationcBusinessService = context.getBean(BeanAnnotationcBusinessService.class);
        System.out.println(beanAnnotationcBusinessService.showMsg());

        System.out.println("--------------------2-----------------------");
        StereotypeBusinessService stereotypeBusinessService = context.getBean(StereotypeBusinessService.class);
        System.out.println(stereotypeBusinessService.showMsg());

        System.out.println("---------------------3----------------------");
        context.registerBean(ProgrammaticallyRegisterService.class);
        ProgrammaticallyRegisterService programmaticallyRegisterService = context.getBean(ProgrammaticallyRegisterService.class);
        System.out.println(programmaticallyRegisterService.showMsg());
    }
}
